INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ('รวบรวมข้อมูลทำ Proposal', 5);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'จัดส่ง Proposal ฉบับสมบูรณ์ให้ Sale / ลุกค้า', 5);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'นำเสนอแผนงาน/โซลูชันให้ลูกค้าฟัง', 3);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ทดสอบอุปกรณ์เซนเซอร์และระบบรวม (Complete Solution)', 1);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'อัปเดตข้อมูลให้ทีมภายในทราบ ภายใน 1-3 วันแรก', 1);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ส่งมอบโซลูชันที่ Verify แล้วให้ทีม Sale / Present ผู้บริหาร', 3);
INSERT INTO pjtrk.ptemplate (task, processid) VALUES ( 'รับโจทย์ / เข้าสำรวจหน้างาน / บันทึกความต้องการลูกค้า (Requirement)', 1);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'รับ Feedback เพื่อปรับปรุง', 3);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ถอดแบบ BOM แยก SW/HW ให้ชัดเจน', 4);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ลูกค้ายืนยันความเข้าใจโซลูชันว่าตรงความต้องการ', 3);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ตรวจสอบและอนุมัติขั้นสุดท้ายโดยผู้บริหาร (Final Review)', 5);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ประชุมรีวิวความถูกต้องทางเทคนิคภายใน (Internal Verification)', 2);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ทำร่างโซลูชัน (Draft Solution)', 1);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ติดตามผลจากลูกค้า (Follow-up)', 6);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'วิเคราะห์ปัญหาหลัก (Pain Point)', 1);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'ลูกค้าเซ็น/อีเมลยืนยันสเปก BOM', 4);
INSERT INTO pjtrk.ptemplate ( task, processid) VALUES ( 'เข้าสำรวจเครื่องจักรโดยละเอียดเพื่อทำ BOM', 4);
INSERT INTO pjtrk.ptemplate (task, processid) VALUES ( 'ประเมินราคา/นำ BOM ไปคำนวณต้นทุนและราคาขาย', 4);
INSERT INTO pjtrk.ptemplate (task, processid) VALUES ( 'ปรับปรุงแก้ไขจุดบกพร่องของโซลูชันให้สมบูรณ์ 100%', 2);
INSERT INTO pjtrk.ptemplate (task, processid) VALUES ( 'อัปเดตสถานะสุดท้าย (รอ/ ชนะ/ แพ้-ยกเลิก)', 6);
